---
title: "MSP_TchrReflection"
author: "BAC"
date: "December 21, 2016"
output: html_document
---


#INSTRUCTIONS:  http://htmlpreview.github.io/?https://raw.githubusercontent.com/jennybc/googlesheets/master/vignettes/basic-usage.html


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(googlesheets)
suppressMessages(library(dplyr))
my_sheets<-gs_ls()
my_sheets  # prints a list of sheets on the Google account
Test1<-gs_title("Treflect_Pre") #assigns a paticular sheet to an R dataframe
Test1
gs_ws_ls(Test1)                         # This command identifies the name of worksheet used in next command

#read data
TestData <-Test1 %>% 
        gs_read(ws = "Form Responses 1")

# read certain cells and not the column names:
TestData <-Test1 %>% 
        gs_read(ws = "Form Responses 1",range=cell_cols(1:8),col_names=FALSE)

head(TestData)
tail(TestData)
# rename all those long variable names
attach(Test1)
# create simple col nuames.
colnames(TestData)<-paste0("Q",1:ncol(TestData))

#http://stackoverflow.com/questions/31768882/unable-to-set-column-names-to-a-subset-of-a-dataframe

```

## R Markdown


```{r test}
attach(Test1)
summary()
```





